version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 3
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: rubocop-minitest
    versions:
    - 0.11.0
  - dependency-name: i18n
    versions:
    - 1.8.9
  - dependency-name: actionpack
    versions:
    - 6.1.2.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 3
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 3
