version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5-node
    parallelism: 3
    steps:
      - checkout
      - run: gem install rails
      - run: bin/test

workflows:
  test:
    jobs:
      - test
