version: 2.1
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.5-node
    parallelism: 1
    steps:
      - checkout
      - run: gem install rails -​-no-document -​-conservative
      - run: git config --global user.email "you@example.com" && git config --global user.name "Your Name"
      - run: sudo apt-get install cmake curl
      - run: bin/test

workflows:
  test:
    jobs:
      - test
