---
version: 2.1
jobs:
  test:
    docker:
      - image: cimg/ruby:3.0-node
        environment:
          DATABASE_URL: postgresql://ubuntu@127.0.0.1/db_test
          BUNDLE_PATH: /home/circleci/project/vendor/bundle
          BUNDLE_JOBS: 4
          BUNDLE_RETRY: 3
          DEBIAN_FRONTEND: noninteractive

      - image: circleci/postgres:alpine-ram
        environment:
          POSTGRES_USER: ubuntu
          POSTGRES_DB: db_test
    parallelism: 2
    steps:
      - checkout
      - restore_cache:
          keys:
            - rails-v2-{{ arch }}-{{ .Revision }}
            - rails-v2-{{ arch }}-
            - rails-v2-

      - ruby/install-deps:
          key: v1-dependencies
          with-cache: false
          path: /home/circleci/project/vendor/bundle

      - node/install-packages:
          app-dir: .
          pkg-manager: yarn
          cache-version: v1

      - run: |
          [[ $CIRCLE_NODE_INDEX == "0" ]] || bin/ci-test
      - run: |
          [[ $CIRCLE_NODE_INDEX == "1" ]] || TEST_APP_TEMPLATE=true bin/ci-test

      - save_cache:
          key: rails-v2-{{ arch }}-{{ .Revision }}
          paths:
            - /home/circleci/project/vendor/bundle
            - /home/circleci/.rubygems
            - /home/circleci/.cache

orbs:
  node: circleci/node@4
  ruby: circleci/ruby@1

workflows:
  commit:
    jobs:
      - hold:
          type: approval
          filters:
            branches:
              ignore:
                - master
      - test:
          requires:
            - hold
  merge:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master

  daily:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
